language: node_js
node_js:
- '4.2'
before_script:
- npm install -g gulp
script: gulp
deploy:
  skip_cleanup: true
  provider: npm
  email: odspnpm@microsoft.com
  api_key:
    secure: hRs/RdrWv6FG9HtGfS02gbtMzfmLO6/7bc1YrMLbrARVUXfyEhx92SFiGHQDHE3WXM1UopmG3C1pHczUl35OyBHMdpXHnmHcwtVmtWsVihSSEZ5mLkXi/SqKXweE2GT5BIM39CsxdHqb+72apbJLwrph1KX6QAsIC+Veyz4naVUazpiJKN+bBHCbl2Nlf/CAB00/RI/aw9pUwHTL4c0+2zITWXyiSklq0Jn0psoe0P8BAb+H2yUVqi8ETPYC34u6iYTRpYhGsZWD/pJvD1kIuDDiJn62tOvwpwMjnbnBAtaGt7fwGViirmqOVRTN9oWRdl1O9eDjckssYShGAMnU272ZRF3ATic3dlH5flEFRmQJe5TkHbZGTFWPdCAcz8X8bNCdygCc17lCVJBxVuyCVA04hkFM4UHhUbvqWBBXTUwpFszWk5k8VUY+tK4n3xWjHiQrjC0C1nVYxjDF4B+uYl70Kc3K2pzb+wBHxIJ9ISWujHUCI8/n/xfgfXT6MoCNhaNcVDFUQbRCgj6eUgQ8jatNVYfvSV4QiCSeTAiEoJSh7DCpSiknMpAkgwG+7wNg4atzktzpvbtsVzADVPWhWG8RQdGPosTftV2pHM3RuhFAoOzVUFtak1bpJM3iA5/xxyPUe7uRs4KDyTo+GHBY/QSm2CTUY6Jo6zdKRyqdwWw=
  on:
    tags: true
    repo: Microsoft/load-themed-styles
