resources:
- repo: self
jobs:
- job: PR Build
  displayName: NodeJS
  condition: succeeded()
  strategy:
    maxParallel: 2
    matrix:
      NodeJs8:
        NodeVersion: 8
      NodeJs10:
        NodeVersion: 10
  steps:
  - task: NodeTool@0
    displayName: 'Use Node $(NodeVersion).x'
    inputs:
      versionSpec: '$(NodeVersion).x'
      checkLatest: true
  - script: 'node common\scripts\install-run-rush.js change --verify'
    displayName: 'Verify Change Logs'
  - script: 'node common\scripts\install-run-rush.js check'
    displayName: 'Rush Check'
  - script: 'node common\scripts\install-run-rush.js install'
    displayName: 'Rush Install'
  - script: 'node common\scripts\install-run-rush.js rebuild --verbose --production'
    displayName: 'Rush Rebuild'
