steps:
  - checkout: self
    persistCredentials: true
  - template: ./build.yaml
  - script: 'node common/scripts/install-run-rush.js publish --apply --publish --include-all --target-branch $(Build.SourceBranchName) --add-commit-details --set-access-level public'
    displayName: 'Rush Publish'
    env:
      NPM_AUTH_TOKEN: $(npmToken)
