parameters:
  - name: VersionPolicyName
    type: string
  - name: BranchName
    type: string
    default: $(Build.SourceBranchName)

steps:
  - script: 'node common/scripts/install-run-rush.js publish --apply --publish --include-all --target-branch release/rush-pr4132 --add-commit-details --set-access-level public --tag pr4132'
    displayName: 'Rush Publish (Policy: ${{ parameters.VersionPolicyName }})'
    env:
      NPM_AUTH_TOKEN: $(npmToken)
