parameters:
  - name: VersionPolicyName
    type: string

steps:
  - script: 'node common/scripts/install-run-rush.js publish --apply --publish --include-all --target-branch release/rush-pr3813 --add-commit-details --set-access-level public --tag pr3813'
    displayName: 'Rush Publish (Policy: ${{ parameters.VersionPolicyName }})'
    env:
      NPM_AUTH_TOKEN: $(npmToken)
