steps:
  - script: 'node repo-scripts/repo-toolbox/lib/start.js record-versions --out-file $(Build.ArtifactStagingDirectory)/published-versions/published-versions.json'
    displayName: 'Rush Install'
  - publish: $(Build.ArtifactStagingDirectory)/published-versions
    artifact: published-versions
    displayName: 'Publish Artifact: published-versions'
